name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessário para obter histórico e tags

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22  # ou sua versão usada

      - name: Instalar dependências
        run: npm ci

      - name: Executar semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
