arrowParens: avoid
bracketSpacing: true
jsxBracketSameLine: false
jsxSingleQuote: true
printWidth: 100
quoteProps: as-needed
semi: true
singleQuote: true
tabWidth: 2
trailingComma: es5
useTabs: false
proseWrap: always
embeddedLanguageFormatting: auto
