services:
- type: web
  name: fotopro-backend
  runtime: node
  repo: https://github.com/FotoProSC/fotopro-backend
  plan: free
  envVars:
  - key: JWT_SECRET
    sync: false
  - key: PORT
    sync: false
  - key: NODE_ENV
    sync: false
  - key: DB_USERNAME
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_NAME
    sync: false
  - key: DB_HOST
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: npm run start
  healthCheckPath: /healthcheck
  autoDeployTrigger: commit
  previews:
    generation: automatic
version: "1"
